/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author useR
 */
public class AddAsisten extends javax.swing.JFrame {

    /**
     * Creates new form AddAsisten
     */
    public AddAsisten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOKAddAsisten = new javax.swing.JButton();
        FormNimAsisten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FormNamaAsisten = new javax.swing.JTextField();
        BtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnOKAddAsisten.setText("OK");
        BtnOKAddAsisten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOKAddAsistenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tambah Asisten");

        FormNamaAsisten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormNamaAsistenActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");

        jLabel1.setText("Masukkan NIM");

        jLabel3.setText("Masukkan Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addGap(40, 40, 40)
                        .addComponent(BtnOKAddAsisten))
                    .addComponent(FormNamaAsisten)
                    .addComponent(FormNimAsisten))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormNimAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormNamaAsisten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOKAddAsisten)
                    .addComponent(BtnBack))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOKAddAsistenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOKAddAsistenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOKAddAsistenActionPerformed

    private void FormNamaAsistenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormNamaAsistenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormNamaAsistenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnOKAddAsisten;
    private javax.swing.JTextField FormNamaAsisten;
    private javax.swing.JTextField FormNimAsisten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBack(){
        return BtnBack;
    }
    public JTextField getFormNamaAsisten() {
        return FormNamaAsisten;
    }

    public JTextField getFormNimAisten() {
        return FormNimAsisten;
    }

    public JButton getOkAddAsisten() {
        return BtnOKAddAsisten;
    }
    
    public String getNim(){
        return FormNimAsisten.getText();
    }
    
    public void setNim(String nim){
        FormNimAsisten.setText(nim);
    }
    
    public String getNama(){
        return FormNamaAsisten.getText();
    }
    
    public void setNama(String nim){
        FormNamaAsisten.setText(nim);
    }
    
    public void addListener(ActionListener e){
        BtnOKAddAsisten.addActionListener(e);
        FormNimAsisten.addActionListener(e);
        FormNamaAsisten.addActionListener(e);
        BtnBack.addActionListener(e);
                
    }

}
