/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author useR
 */
public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddMahasiswa = new javax.swing.JButton();
        btnAddAsisten = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLoginMhs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddMahasiswa.setText("AddMahasiswa");

        btnAddAsisten.setText("AddAsisten ");

        btnLogin.setText("Log In Asisten");

        jLabel1.setText("Main Menu");

        btnLoginMhs.setText("Log In Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAsisten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(btnAddAsisten)
                .addGap(31, 31, 31)
                .addComponent(btnAddMahasiswa)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnLoginMhs)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAsisten;
    private javax.swing.JButton btnAddMahasiswa;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginMhs;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    public JButton getBtnAddAsisten() {
        return btnAddAsisten;
    }

    public JButton getBtnAddMahasiswa() {
        return btnAddMahasiswa;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }  
    
    public JButton getBtnLoginMhs(){
        return btnLoginMhs;
    }
    
    public void addListener(ActionListener e) {
        btnAddAsisten.addActionListener(e);
        btnAddMahasiswa.addActionListener(e);
        btnLogin.addActionListener(e);
    }
}


