/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author useR
 */
public class MenuAsisten extends javax.swing.JFrame {

    /**
     * Creates new form MenuAsisten
     */
    public MenuAsisten() {
        initComponents();
    }

    public JButton getBtnLihatDaftarTubes() {
        return BtnLihatDaftarTubes;
    }

    public JButton getBtnLogout() {
        return BtnLogout;
    }

    public JButton getBtnTambahTubes() {
        return BtnTambahTubes;
    }

    public void addListener(ActionListener e){
        BtnLihatDaftarTubes.addActionListener(e);
        BtnLogout.addActionListener(e);
        BtnTambahTubes.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnTambahTubes = new javax.swing.JButton();
        BtnLihatDaftarTubes = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Asisten");

        BtnTambahTubes.setText("Tambah Tubes");

        BtnLihatDaftarTubes.setText("Lihat List Tubes");

        BtnLogout.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnTambahTubes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnLihatDaftarTubes))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(BtnTambahTubes)
                .addGap(18, 18, 18)
                .addComponent(BtnLihatDaftarTubes)
                .addGap(18, 18, 18)
                .addComponent(BtnLogout)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLihatDaftarTubes;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnTambahTubes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
